version: "3.7"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site/conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    extra_hosts:
      - "php-docker.local:127.0.0.1"
  php:
    image: php:8-fpm
    volumes:
      - ./code:/code
